name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Function
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: funrepeat-assignment
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        export_default_credentials: true

    - name: Deploy to Google Cloud Functions
      if: github.ref == 'refs/heads/main'
      run: |
        gcloud functions deploy backup_gcf_call --entry-point backup_gcf_call --runtime nodejs20 --trigger-http --allow-unauthenticated --region us-central1
