name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main
      - fix

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        project_id: funrepeat-assignment
        export_default_credentials: true

    - name: Deploy to GCF (fix branch)
      if: github.ref == 'refs/heads/fix'
      run: |
        gcloud functions deploy backup_gcf_call --timeout=3600s --gen2 --runtime nodejs20 --region us-central1 --trigger-http --allow-unauthenticated

    - name: Deploy to GCF (main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        gcloud functions deploy backup_gcf_call --timeout=3600s --gen2 --runtime nodejs20 --region us-central1 --trigger-http --allow-unauthenticated